### PR TITLE
No need for trailing .js as per docs.

### PR DESCRIPTION
**Pull request by JohnMcLear**
plz merge, update package.json and publish

### CODE REVIEW

**Comment by Yaco** [comment]
Also remove the ".js" in https://github.com/marcelklehr/ep_push2delete/blob/master/static/js/delete_button.js#L1

**Comment by marcelklehr** [comment]
Is it required to skip the trailing .js? I always thought it works both ways...

**Comment by JohnMcLear** [comment]
We no longer support the trailing .js @marcelklehr  :)

**Comment by marcelklehr** [comment]
okies.

**Comment by marcelklehr** [comment]
done.

**Pull request merged**
